# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/win/linux/stereovision

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/win/linux/stereovision

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/win/linux/stereovision/CMakeFiles /mnt/win/linux/stereovision/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/win/linux/stereovision/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named StereoVision

# Build rule for target.
StereoVision: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 StereoVision
.PHONY : StereoVision

# fast build rule for target.
StereoVision/fast:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/build
.PHONY : StereoVision/fast

src/CalibEngine.o: src/CalibEngine.cpp.o

.PHONY : src/CalibEngine.o

# target to build an object file
src/CalibEngine.cpp.o:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/CalibEngine.cpp.o
.PHONY : src/CalibEngine.cpp.o

src/CalibEngine.i: src/CalibEngine.cpp.i

.PHONY : src/CalibEngine.i

# target to preprocess a source file
src/CalibEngine.cpp.i:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/CalibEngine.cpp.i
.PHONY : src/CalibEngine.cpp.i

src/CalibEngine.s: src/CalibEngine.cpp.s

.PHONY : src/CalibEngine.s

# target to generate assembly for a file
src/CalibEngine.cpp.s:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/CalibEngine.cpp.s
.PHONY : src/CalibEngine.cpp.s

src/ChessboardDetectEngine.o: src/ChessboardDetectEngine.cpp.o

.PHONY : src/ChessboardDetectEngine.o

# target to build an object file
src/ChessboardDetectEngine.cpp.o:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/ChessboardDetectEngine.cpp.o
.PHONY : src/ChessboardDetectEngine.cpp.o

src/ChessboardDetectEngine.i: src/ChessboardDetectEngine.cpp.i

.PHONY : src/ChessboardDetectEngine.i

# target to preprocess a source file
src/ChessboardDetectEngine.cpp.i:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/ChessboardDetectEngine.cpp.i
.PHONY : src/ChessboardDetectEngine.cpp.i

src/ChessboardDetectEngine.s: src/ChessboardDetectEngine.cpp.s

.PHONY : src/ChessboardDetectEngine.s

# target to generate assembly for a file
src/ChessboardDetectEngine.cpp.s:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/ChessboardDetectEngine.cpp.s
.PHONY : src/ChessboardDetectEngine.cpp.s

src/ConfigSerializer.o: src/ConfigSerializer.cpp.o

.PHONY : src/ConfigSerializer.o

# target to build an object file
src/ConfigSerializer.cpp.o:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/ConfigSerializer.cpp.o
.PHONY : src/ConfigSerializer.cpp.o

src/ConfigSerializer.i: src/ConfigSerializer.cpp.i

.PHONY : src/ConfigSerializer.i

# target to preprocess a source file
src/ConfigSerializer.cpp.i:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/ConfigSerializer.cpp.i
.PHONY : src/ConfigSerializer.cpp.i

src/ConfigSerializer.s: src/ConfigSerializer.cpp.s

.PHONY : src/ConfigSerializer.s

# target to generate assembly for a file
src/ConfigSerializer.cpp.s:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/ConfigSerializer.cpp.s
.PHONY : src/ConfigSerializer.cpp.s

src/CvUtil.o: src/CvUtil.cpp.o

.PHONY : src/CvUtil.o

# target to build an object file
src/CvUtil.cpp.o:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/CvUtil.cpp.o
.PHONY : src/CvUtil.cpp.o

src/CvUtil.i: src/CvUtil.cpp.i

.PHONY : src/CvUtil.i

# target to preprocess a source file
src/CvUtil.cpp.i:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/CvUtil.cpp.i
.PHONY : src/CvUtil.cpp.i

src/CvUtil.s: src/CvUtil.cpp.s

.PHONY : src/CvUtil.s

# target to generate assembly for a file
src/CvUtil.cpp.s:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/CvUtil.cpp.s
.PHONY : src/CvUtil.cpp.s

src/ImgSourceCamera.o: src/ImgSourceCamera.cpp.o

.PHONY : src/ImgSourceCamera.o

# target to build an object file
src/ImgSourceCamera.cpp.o:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/ImgSourceCamera.cpp.o
.PHONY : src/ImgSourceCamera.cpp.o

src/ImgSourceCamera.i: src/ImgSourceCamera.cpp.i

.PHONY : src/ImgSourceCamera.i

# target to preprocess a source file
src/ImgSourceCamera.cpp.i:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/ImgSourceCamera.cpp.i
.PHONY : src/ImgSourceCamera.cpp.i

src/ImgSourceCamera.s: src/ImgSourceCamera.cpp.s

.PHONY : src/ImgSourceCamera.s

# target to generate assembly for a file
src/ImgSourceCamera.cpp.s:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/ImgSourceCamera.cpp.s
.PHONY : src/ImgSourceCamera.cpp.s

src/Logger.o: src/Logger.cpp.o

.PHONY : src/Logger.o

# target to build an object file
src/Logger.cpp.o:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/Logger.cpp.o
.PHONY : src/Logger.cpp.o

src/Logger.i: src/Logger.cpp.i

.PHONY : src/Logger.i

# target to preprocess a source file
src/Logger.cpp.i:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/Logger.cpp.i
.PHONY : src/Logger.cpp.i

src/Logger.s: src/Logger.cpp.s

.PHONY : src/Logger.s

# target to generate assembly for a file
src/Logger.cpp.s:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/Logger.cpp.s
.PHONY : src/Logger.cpp.s

src/Rectifier.o: src/Rectifier.cpp.o

.PHONY : src/Rectifier.o

# target to build an object file
src/Rectifier.cpp.o:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/Rectifier.cpp.o
.PHONY : src/Rectifier.cpp.o

src/Rectifier.i: src/Rectifier.cpp.i

.PHONY : src/Rectifier.i

# target to preprocess a source file
src/Rectifier.cpp.i:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/Rectifier.cpp.i
.PHONY : src/Rectifier.cpp.i

src/Rectifier.s: src/Rectifier.cpp.s

.PHONY : src/Rectifier.s

# target to generate assembly for a file
src/Rectifier.cpp.s:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/Rectifier.cpp.s
.PHONY : src/Rectifier.cpp.s

src/Reprojector3D.o: src/Reprojector3D.cpp.o

.PHONY : src/Reprojector3D.o

# target to build an object file
src/Reprojector3D.cpp.o:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/Reprojector3D.cpp.o
.PHONY : src/Reprojector3D.cpp.o

src/Reprojector3D.i: src/Reprojector3D.cpp.i

.PHONY : src/Reprojector3D.i

# target to preprocess a source file
src/Reprojector3D.cpp.i:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/Reprojector3D.cpp.i
.PHONY : src/Reprojector3D.cpp.i

src/Reprojector3D.s: src/Reprojector3D.cpp.s

.PHONY : src/Reprojector3D.s

# target to generate assembly for a file
src/Reprojector3D.cpp.s:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/Reprojector3D.cpp.s
.PHONY : src/Reprojector3D.cpp.s

src/RunMode.o: src/RunMode.cpp.o

.PHONY : src/RunMode.o

# target to build an object file
src/RunMode.cpp.o:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/RunMode.cpp.o
.PHONY : src/RunMode.cpp.o

src/RunMode.i: src/RunMode.cpp.i

.PHONY : src/RunMode.i

# target to preprocess a source file
src/RunMode.cpp.i:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/RunMode.cpp.i
.PHONY : src/RunMode.cpp.i

src/RunMode.s: src/RunMode.cpp.s

.PHONY : src/RunMode.s

# target to generate assembly for a file
src/RunMode.cpp.s:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/RunMode.cpp.s
.PHONY : src/RunMode.cpp.s

src/SbmProcessor.o: src/SbmProcessor.cpp.o

.PHONY : src/SbmProcessor.o

# target to build an object file
src/SbmProcessor.cpp.o:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/SbmProcessor.cpp.o
.PHONY : src/SbmProcessor.cpp.o

src/SbmProcessor.i: src/SbmProcessor.cpp.i

.PHONY : src/SbmProcessor.i

# target to preprocess a source file
src/SbmProcessor.cpp.i:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/SbmProcessor.cpp.i
.PHONY : src/SbmProcessor.cpp.i

src/SbmProcessor.s: src/SbmProcessor.cpp.s

.PHONY : src/SbmProcessor.s

# target to generate assembly for a file
src/SbmProcessor.cpp.s:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/SbmProcessor.cpp.s
.PHONY : src/SbmProcessor.cpp.s

src/SbmTuner.o: src/SbmTuner.cpp.o

.PHONY : src/SbmTuner.o

# target to build an object file
src/SbmTuner.cpp.o:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/SbmTuner.cpp.o
.PHONY : src/SbmTuner.cpp.o

src/SbmTuner.i: src/SbmTuner.cpp.i

.PHONY : src/SbmTuner.i

# target to preprocess a source file
src/SbmTuner.cpp.i:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/SbmTuner.cpp.i
.PHONY : src/SbmTuner.cpp.i

src/SbmTuner.s: src/SbmTuner.cpp.s

.PHONY : src/SbmTuner.s

# target to generate assembly for a file
src/SbmTuner.cpp.s:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/SbmTuner.cpp.s
.PHONY : src/SbmTuner.cpp.s

src/SgbmProcessor.o: src/SgbmProcessor.cpp.o

.PHONY : src/SgbmProcessor.o

# target to build an object file
src/SgbmProcessor.cpp.o:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/SgbmProcessor.cpp.o
.PHONY : src/SgbmProcessor.cpp.o

src/SgbmProcessor.i: src/SgbmProcessor.cpp.i

.PHONY : src/SgbmProcessor.i

# target to preprocess a source file
src/SgbmProcessor.cpp.i:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/SgbmProcessor.cpp.i
.PHONY : src/SgbmProcessor.cpp.i

src/SgbmProcessor.s: src/SgbmProcessor.cpp.s

.PHONY : src/SgbmProcessor.s

# target to generate assembly for a file
src/SgbmProcessor.cpp.s:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/SgbmProcessor.cpp.s
.PHONY : src/SgbmProcessor.cpp.s

src/StereoProcessor.o: src/StereoProcessor.cpp.o

.PHONY : src/StereoProcessor.o

# target to build an object file
src/StereoProcessor.cpp.o:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/StereoProcessor.cpp.o
.PHONY : src/StereoProcessor.cpp.o

src/StereoProcessor.i: src/StereoProcessor.cpp.i

.PHONY : src/StereoProcessor.i

# target to preprocess a source file
src/StereoProcessor.cpp.i:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/StereoProcessor.cpp.i
.PHONY : src/StereoProcessor.cpp.i

src/StereoProcessor.s: src/StereoProcessor.cpp.s

.PHONY : src/StereoProcessor.s

# target to generate assembly for a file
src/StereoProcessor.cpp.s:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/StereoProcessor.cpp.s
.PHONY : src/StereoProcessor.cpp.s

src/SysUtil.o: src/SysUtil.cpp.o

.PHONY : src/SysUtil.o

# target to build an object file
src/SysUtil.cpp.o:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/SysUtil.cpp.o
.PHONY : src/SysUtil.cpp.o

src/SysUtil.i: src/SysUtil.cpp.i

.PHONY : src/SysUtil.i

# target to preprocess a source file
src/SysUtil.cpp.i:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/SysUtil.cpp.i
.PHONY : src/SysUtil.cpp.i

src/SysUtil.s: src/SysUtil.cpp.s

.PHONY : src/SysUtil.s

# target to generate assembly for a file
src/SysUtil.cpp.s:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/SysUtil.cpp.s
.PHONY : src/SysUtil.cpp.s

src/Util3D.o: src/Util3D.cpp.o

.PHONY : src/Util3D.o

# target to build an object file
src/Util3D.cpp.o:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/Util3D.cpp.o
.PHONY : src/Util3D.cpp.o

src/Util3D.i: src/Util3D.cpp.i

.PHONY : src/Util3D.i

# target to preprocess a source file
src/Util3D.cpp.i:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/Util3D.cpp.i
.PHONY : src/Util3D.cpp.i

src/Util3D.s: src/Util3D.cpp.s

.PHONY : src/Util3D.s

# target to generate assembly for a file
src/Util3D.cpp.s:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/Util3D.cpp.s
.PHONY : src/Util3D.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/StereoVision.dir/build.make CMakeFiles/StereoVision.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... StereoVision"
	@echo "... src/CalibEngine.o"
	@echo "... src/CalibEngine.i"
	@echo "... src/CalibEngine.s"
	@echo "... src/ChessboardDetectEngine.o"
	@echo "... src/ChessboardDetectEngine.i"
	@echo "... src/ChessboardDetectEngine.s"
	@echo "... src/ConfigSerializer.o"
	@echo "... src/ConfigSerializer.i"
	@echo "... src/ConfigSerializer.s"
	@echo "... src/CvUtil.o"
	@echo "... src/CvUtil.i"
	@echo "... src/CvUtil.s"
	@echo "... src/ImgSourceCamera.o"
	@echo "... src/ImgSourceCamera.i"
	@echo "... src/ImgSourceCamera.s"
	@echo "... src/Logger.o"
	@echo "... src/Logger.i"
	@echo "... src/Logger.s"
	@echo "... src/Rectifier.o"
	@echo "... src/Rectifier.i"
	@echo "... src/Rectifier.s"
	@echo "... src/Reprojector3D.o"
	@echo "... src/Reprojector3D.i"
	@echo "... src/Reprojector3D.s"
	@echo "... src/RunMode.o"
	@echo "... src/RunMode.i"
	@echo "... src/RunMode.s"
	@echo "... src/SbmProcessor.o"
	@echo "... src/SbmProcessor.i"
	@echo "... src/SbmProcessor.s"
	@echo "... src/SbmTuner.o"
	@echo "... src/SbmTuner.i"
	@echo "... src/SbmTuner.s"
	@echo "... src/SgbmProcessor.o"
	@echo "... src/SgbmProcessor.i"
	@echo "... src/SgbmProcessor.s"
	@echo "... src/StereoProcessor.o"
	@echo "... src/StereoProcessor.i"
	@echo "... src/StereoProcessor.s"
	@echo "... src/SysUtil.o"
	@echo "... src/SysUtil.i"
	@echo "... src/SysUtil.s"
	@echo "... src/Util3D.o"
	@echo "... src/Util3D.i"
	@echo "... src/Util3D.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

